spring:
  application:
    name: UserServices
  config:
    import: optional:configserver:http://localhost:9090
  mail:
    host: smtp.gmail.com
    port: 587
    username: pd.pavanirrinki@gmail.com
    password: jdmn jtxy pzez rbtr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9091
