spring:
  application:
    name: UserServices
  config:
    import: optional:configserver:http://localhost:9090
  mail:
    host: smtp.gmail.com
    port: 587
    username: pd.pavanirrinki@gmail.com
    password: jdmn jtxy pzez rbtr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://root:fedVEmgyCzNfTfpHYmZzgQMnQSSIZttd@mysql-dtvs.railway.internal:3306/railway
    username: root
    password: fedVEmgyCzNfTfpHYmZzgQMnQSSIZttd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9091
